/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2019-04-01 16:16:43
*/
import { LampResponsibility } from './LampResponsibility';
import { IDisposable } from 'dotup-ts-types';

export interface ILamp extends IDisposable {
  readonly responsibility: LampResponsibility;
  powerOnMs(durationMs: number): Promise<void>;
  blink(count: number, intervalMs: number): Promise<void>;
  powerOff(): Promise<void>;
  powerOn(): Promise<void>;
}
